version: '3'
services:
    postres:
        image: postgres:13
        container_name: postgres_weather_etl_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            -   "5432:5432"
        volumes:
            -   postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:

